# Generated by Django 3.1.2 on 2020-11-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('photo', models.ImageField(default='images/default.png', null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cv',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre de la compétance')),
                ('note', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='note de la compétance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
            ],
            options={
                'verbose_name': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='langue')),
                ('note_parler', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='note parler')),
                ('note_ecrit', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='note écrit')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
            ],
            options={
                'verbose_name': 'langue',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name="Titre de l'activité")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
            ],
            options={
                'verbose_name': 'activité',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre de la formation')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('etablissement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etablissement')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'licence'), (2, 'master'), (0, 'bac'), (3, 'doctorat')], default=1, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
            ],
            options={
                'verbose_name': 'formation',
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name="Titre de l'experience")),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('etablissement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etablissement')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
            ],
            options={
                'verbose_name': 'experience',
                'ordering': ['begin_date'],
            },
        ),
    ]
