# Generated by Django 3.1.2 on 2021-02-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre de la formation')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('facility', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etablissement')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'licence'), (2, 'master'), (0, 'bac'), (3, 'doctorat')], default=1, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education',
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name="Titre de l'experience")),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('facility', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etablissement')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experience',
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name="Titre de l'activité")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activité',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Language')),
                ('note_parler', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='note parler')),
                ('note_ecrit', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='note écrit')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre de la compétance')),
                ('note', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='note de la compétance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('educations', models.ManyToManyField(to='core.Education')),
                ('experiences', models.ManyToManyField(to='core.Experience')),
                ('hobbies', models.ManyToManyField(to='core.Hobby')),
                ('languages', models.ManyToManyField(to='core.Language')),
                ('skills', models.ManyToManyField(to='core.Skill')),
            ],
            options={
                'verbose_name': 'Resume',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='nom')),
                ('first_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='prenom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('adress', models.CharField(blank=True, max_length=50, null=True, verbose_name='adresse')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
