# Generated by Django 3.1.2 on 2020-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(to='core.Skill'),
        ),
    ]
