# Generated by Django 3.1.2 on 2020-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201128_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='hobbie',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='cv',
        ),
        migrations.AddField(
            model_name='cv',
            name='experiences',
            field=models.ManyToManyField(to='core.Experience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='formations',
            field=models.ManyToManyField(to='core.Formation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='hobbies',
            field=models.ManyToManyField(to='core.Hobbie'),
        ),
        migrations.AddField(
            model_name='cv',
            name='langues',
            field=models.ManyToManyField(to='core.Langue'),
        ),
    ]
