# Generated by Django 3.1.2 on 2020-10-20 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_langue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre de la formation')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('etablissement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etablissement')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'licence'), (2, 'master'), (0, 'bac'), (3, 'doctorat')], default=1, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formation',
                'ordering': ['begin_date'],
            },
        ),
    ]
