# Generated by Django 3.1.2 on 2020-10-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name="Titre de l'experience")),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('etablissement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etablissement')),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experience',
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/default.png', null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.experience')),
                ('formations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formation')),
                ('hobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hobbie')),
                ('langages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.langue')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={
                'verbose_name': 'Cv',
            },
        ),
    ]
