# Generated by Django 3.1.2 on 2020-10-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cv_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='formations',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='langages',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='cv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobbie',
            name='cv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='langue',
            name='cv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cv'),
            preserve_default=False,
        ),
    ]
