# Generated by Django 3.1.2 on 2020-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201020_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ManyToManyField(to='core.Cv'),
        ),
    ]
